### ISSUE TITLE
C++ modules `clang-tidy` fails

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#64]
I don't know if it is `clang-tidy` specific or `cmake 3.26.3` or `clang-tidy 16.0.0` issue.
The issue shown is:
```
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/project/cmake-build-pre-commit/_configuring'
```

**Comment by Takishima** [comment]
This does seem like an issue, I will try to look into this.

**Comment by Takishima** [comment]
In the mean time, you might want to try to add the serial: true` entry in your pre-commit configuration file.

**Comment by LecrisUT** [comment]
Yes, it worked. It was `require_serial: true`.
Here's a traceback that could help:
```
Traceback (most recent call last):
  File "/home/.cache/pre-commit/repougxmkjf2/py_env-python3.11/bin/cmake-pc-clang-tidy-hook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/.cache/pre-commit/repougxmkjf2/py_env-python3.11/lib/python3.11/site-packages/cmake_pc_hooks/clang_tidy.py", line 77, in main
    cmd.run()
  File "/home/.cache/pre-commit/repougxmkjf2/py_env-python3.11/lib/python3.11/site-packages/cmake_pc_hooks/_utils.py", line 273, in run
    self.run_cmake_configure()
  File "/home/.cache/pre-commit/repougxmkjf2/py_env-python3.11/lib/python3.11/site-packages/cmake_pc_hooks/_utils.py", line 354, in run_cmake_configure
    configuring.unlink()
  File "/usr/lib64/python3.11/pathlib.py", line 1147, in unlink
    os.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/project/cmake-build-pre-commit/_configuring'
```

**Comment by LecrisUT** [comment]
Note, that `clang-tidy` fails on with modules. Might be a cmake issue though:
https://github.com/llvm/llvm-project/issues/62258

**Comment by Takishima** [comment]
Good to know. Worst case, users can exclude those files in the pre-commit configuration file.
